bioimageio_core_version: 0.5.3post2
bioimageio_spec_version: 0.4.5post6
error: 'Failed to download https://zenodo.org/api/files/da7b84a8-f43a-4a24-93cd-9716be7b2655/unet_pancreatic_cell_segmentation.h5
  (404 Client Error: NOT FOUND for url: https://zenodo.org/api/files/da7b84a8-f43a-4a24-93cd-9716be7b2655/unet_pancreatic_cell_segmentation.h5)'
name: reproduce test outputs with ilastik 1.4.0b27 using keras_hdf5 weights
reason: error
status: failed
traceback: ["  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_tests.py\",
    line 39, in test_model\n    model_rdf, weights_priority_order=None if weight_format
    is None else [weight_format]\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_io/io_.py\",
    line 57, in load_resource_description\n    rd: ResourceDescription = resolve_raw_resource_description(raw_rd=raw_rd,
    nodes_module=nodes)\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_io/utils.py\",
    line 112, in resolve_raw_resource_description\n    rd = UriNodeTransformer(root_path=raw_rd.root_path,
    uri_only_if_in_package=uri_only_if_in_package).transform(raw_rd)\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
    line 54, in transform\n    return transformer(node, **kwargs)  # noqa\n", "  File
    \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
    line 86, in generic_transformer\n    node, **{n: self.transform(value, name=n,
    parent=node) for n, value in iter_fields(node)}\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
    line 86, in <dictcomp>\n    node, **{n: self.transform(value, name=n, parent=node)
    for n, value in iter_fields(node)}\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
    line 54, in transform\n    return transformer(node, **kwargs)  # noqa\n", "  File
    \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
    line 63, in transform_dict\n    return {key: self.transform(value, **kwargs) for
    key, value in node.items()}\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
    line 63, in <dictcomp>\n    return {key: self.transform(value, **kwargs) for key,
    value in node.items()}\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
    line 54, in transform\n    return transformer(node, **kwargs)  # noqa\n", "  File
    \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
    line 86, in generic_transformer\n    node, **{n: self.transform(value, name=n,
    parent=node) for n, value in iter_fields(node)}\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
    line 86, in <dictcomp>\n    node, **{n: self.transform(value, name=n, parent=node)
    for n, value in iter_fields(node)}\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
    line 54, in transform\n    return transformer(node, **kwargs)  # noqa\n", "  File
    \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
    line 206, in transform_URI\n    local_path = _resolve_source(node, root_path=self.root_path)\n",
  "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/functools.py\", line
    840, in wrapper\n    return dispatch(args[0].__class__)(*args, **kw)\n", "  File
    \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/_resolve_source.py\",
    line 212, in _resolve_source_uri_node\n    local_path = _download_url(path_or_remote_uri,
    output)\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/_resolve_source.py\",
    line 396, in _download_url\n    raise RuntimeError(f\"Failed to download {uri}
    ({e})\")\n"]
