bioimageio_core_version: 0.5.1
bioimageio_spec_version: 0.4.5post3
error: No module named 'onnxruntime'
name: reproduce test outputs with ilastik 1.4.0b26 using onnx weights
reason: error
status: failed
traceback: ["  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_tests.py\",
    line 148, in test_resource\n    bioimageio_model=model, devices=devices, weight_format=weight_format\n",
  "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\",
    line 159, in create_prediction_pipeline\n    bioimageio_model=bioimageio_model,
    devices=devices, weight_format=weight_format\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py\",
    line 113, in create_model_adapter\n    adapter_cls = _get_model_adapter(weight)\n",
  "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py\",
    line 138, in _get_model_adapter\n    from ._onnx_model_adapter import ONNXModelAdapter\n",
  "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_onnx_model_adapter.py\",
    line 5, in <module>\n    import onnxruntime as rt\n"]
