bioimageio_core_version: 0.5.1
bioimageio_spec_version: 0.4.5post3
error: Cannot load file containing pickled data when allow_pickle=False
name: reproduce test outputs with ilastik 1.4.0b26 using tensorflow_js weights
reason: error
status: failed
traceback: ["  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_tests.py\",
    line 126, in test_resource\n    inputs = [np.load(str(in_path)) for in_path in
    model.test_inputs]\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_tests.py\",
    line 126, in <listcomp>\n    inputs = [np.load(str(in_path)) for in_path in model.test_inputs]\n",
  "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/numpy/lib/npyio.py\",
    line 445, in load\n    raise ValueError(\"Cannot load file containing pickled
    data \"\n"]
